version: '3'

services:
  overture:
    restart: always
    image: coolrc/overture
    volumes:
      - ./config:/overture

  doh:
    restart: always
    image: coolrc/dns-over-https
    volumes:
      - ./doh-server.conf:/doh-server.conf

  nginx:
    restart: always
    image: nginx:stable-alpine
    depends_on:
      - overture
      - doh
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/dns.coolrc.top/fullchain.pem:/ssl/fullchain.pem
      - /etc/letsencrypt/live/dns.coolrc.top/privkey.pem:/ssl/privkey.pem
    ports:
      - "853:853"
      - "443:443"

