version: '3'

services:
  dns:
    restart: always
    image: coolrc/ts-dns
    volumes:
      - ./config:/root/config
      - ./ts-dns.toml:/root/ts-dns.toml
    healthcheck:
      test: dig @127.0.0.1 -p 53 www.google.com || exit 1
      interval: 30s
      timeout: 2s
      retries: 5
    labels:
      - "autoheal=true"


  doh:
    restart: always
    image: satishweb/doh-server
    environment:
      DEBUG: "0"
      # Upstream DNS server: proto:host:port
      # We are using OpenDNS DNS servers as default,
      # Here is the list of addresses: https://use.opendns.com/
      UPSTREAM_DNS_SERVER: "udp:dns:53"
      DOH_HTTP_PREFIX: "/dns-query"
      DOH_SERVER_LISTEN: ":8053"
      DOH_SERVER_TIMEOUT: "5"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "false"
      # You can add more variables here or as docker secret and entrypoint
      # script will replace them inside doh-server.conf file
    #volumes:
    #  - ./doh-server.conf:/server/doh-server.conf
    healthcheck:
      #disable: true
      test: wget --no-verbose --tries=1 -O - "127.0.0.1:8053/dns-query?name=www.google.com&type=A" || exit 1
      interval: 2m
      timeout: 3s
      retries: 3
    ports:
      - "8053:8053"
        #labels:
      #- "autoheal=true"


  nginx:
    restart: always
    image: nginx:stable-alpine
    user: root
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /root/caddy-https-config/.caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/dns.coolrc.top/:/ssl/
    # 绑定caddy的数据，让caddy自动更新证书
    #    healthcheck:
    # test: curl "https://127.0.0.1/dns-query?name=baidu.com&type=A" -k || exit 1
     # interval: 2m
     # timeout: 3s
     # retries: 3
    ports:
      - "853:853"
        #    labels:
        #- "autoheal=true"

  autoheal:
    restart: always
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal

