version: '3'

services:
  overture:
    restart: always
    image: coolrc/overture
    volumes:
      - ./config:/overture
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "-p", "5353", "www.baidu.com", "||", "exit", "1"]
      interval: 30s
      timeout: 2s
      retries: 3

  doh:
    restart: always
    image: satishweb/doh-server
    volumes:
      - ./doh-server.conf:/server/doh-server.conf

  nginx:
    restart: always
    image: nginx:stable-alpine
    user: root
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/dns.coolrc.top/fullchain.pem:/ssl/fullchain.pem
      - /etc/letsencrypt/live/dns.coolrc.top/privkey.pem:/ssl/privkey.pem
    ports:
      - "853:853"
      - "443:443"

