version: '3'

services:
  overture:
    restart: always
    image: coolrc/overture
    volumes:
      - ./config:/overture
    healthcheck:
      test: dig @127.0.0.1 -p 5353 www.google.com || exit 1
      interval: 30s
      timeout: 2s
      retries: 3
    labels:
      - "autoheal=true"

  doh:
    restart: always
    image: satishweb/doh-server
    volumes:
      - ./doh-server.conf:/server/doh-server.conf
    healthcheck:
      #disable: true
      test: wget -O - 127.0.0.1:8053/dns-query?name=www.google.com&type=A || exit 1
      interval: 2m
      timeout: 3s
      retries: 3
    labels:
      - "autoheal=true"

  doh2:
    restart: always
    image: satishweb/doh-server
    volumes:
      - ./doh-server.conf:/server/doh-server.conf
    healthcheck:
      #disable: true
      test: wget -O - 127.0.0.1:8053/dns-query?name=www.google.com&type=A || exit 1
      interval: 2m
      timeout: 3s
      retries: 3
    labels:
      - "autoheal=true"

  nginx:
    restart: always
    image: nginx:stable-alpine
    user: root
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/dns.coolrc.top/fullchain.pem:/ssl/fullchain.pem
      - /etc/letsencrypt/live/dns.coolrc.top/privkey.pem:/ssl/privkey.pem
    healthcheck:
      test: curl "https://127.0.0.1/dns-query?name=baidu.com&type=A" -k || exit 1
      interval: 2m
      timeout: 3s
      retries: 3
    ports:
      - "853:853"
      - "443:443"
    labels:
      - "autoheal=true"

  autoheal:
    restart: always
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal

